# Phase 12 intelligence configuration.

SMA_FAST_PERIOD = 5
SMA_SLOW_PERIOD = 10

EMA_FAST_PERIOD = 5
EMA_SLOW_PERIOD = 10

RSI_PERIOD = 14
ATR_PERIOD = 14

MOMENTUM_PERIOD = 5

BULLISH_THRESHOLD = 0.25
BEARISH_THRESHOLD = -0.25

MIN_CONFIDENCE = 0.55

TECHNICAL_WEIGHT = 0.55
REGIME_WEIGHT = 0.20
SENTIMENT_WEIGHT = 0.25

ENABLE_AI_LAYER = True
