TRAINING_SIZE = 20
TEST_SIZE = 10
STEP_SIZE = 10

MIN_TRAINING_SIZE = 10
MIN_TEST_SIZE = 5

REPORT_DIRECTORY = "reports/phase17"

DEFAULT_SYMBOL = "NIFTY"
DEFAULT_QUANTITY = 1

OVERFITTING_THRESHOLD = 0.50
