"""
Phase 22 controlled deployment configuration.

Live trading is intentionally disabled.
"""

PAPER_MODE = True
LIVE_TRADING_ENABLED = False
REAL_BROKER_ENABLED = False

DEFAULT_SYMBOL = "NIFTY"
DEFAULT_QUANTITY = 1

MAX_ORDER_QUANTITY = 10
MAX_DAILY_TRADES = 20
MAX_DAILY_LOSS = 5000.0

REQUIRE_PHASE17_VALIDATION = True
REQUIRE_PHASE18_ROBUSTNESS = True
REQUIRE_PHASE19_PAPER_VALIDATION = True
REQUIRE_PHASE20_READINESS = True
REQUIRE_PHASE21_EXECUTION_CERTIFICATION = True

REQUIRE_KILL_SWITCH = True
REQUIRE_AUDIT_LOGGING = True

REPORT_DIRECTORY = "reports/phase22"
REPORT_FILENAME = "phase22_deployment_readiness_report.json"
AUDIT_FILENAME = "phase22_deployment_audit.log"

DEPLOYMENT_NAME = "TRADING_AGENT_PHASE22"

ENVIRONMENT = "PAPER"

ALLOWED_ENVIRONMENTS = (
    "PAPER",
    "STAGING",
    "LIVE",
)

LIVE_CONFIRMATION_REQUIRED = True

VERSION = "22.0.0"
